a1 = int(input("Enter a1: "))
a2  = int(input("Enter a2"))
b1 = int(input("enter b1"))
b2 = int(input("enter b2"))
print(a1*b1 + a2*b2)
print("Checking question 5 of assignment 2 of git")
print("Changes in the main branch..")
